name: Publish Dev Container Features and Templates

on: push

jobs:
  publish-features:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish Dev Container Features
        uses: devcontainers/action@v1
        with:
          publish-features: "true"
          base-path-to-features: "./features"
          features-namespace: "SituDevelopment/features"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-templates:
    needs: [publish-features]
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish Dev Container Templates
        uses: devcontainers/action@v1
        with:
          publish-templates: "true"
          base-path-to-templates: "./templates"
          templates-namespace: "SituDevelopment/templates"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
